server:
  port: 8080

spring:
  application:
    name: ip-service
  datasource:
    url: jdbc:h2:mem:user-service-db;DB_CLOSE_DELAY=-1;
    username: admin
    password: 123asd
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      platform: h2
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#ipapi
ipapi:
  baseUrl: http://api.ipapi.com/
  key: 0fce741b705501e89f51ef2ac280a446

#apilayer
ip-to-location:
  baseUrl: https://api.apilayer.com/
  key: jicFjLsCjfrjGQXmoH14JCBWcf3SnND9

#exchangeratesapi
exchange-rates:
  baseUrl: https://api.apilayer.com/exchangerates_data/
  key: EBmwztnFLhfDwHKeC1e8vXimZS4eZJcw
